<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE history [
    <!ELEMENT history (etap*)>
    <!ELEMENT etap (name,text,img)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT text (#PCDATA)>
    <!ELEMENT img (#PCDATA)>
]>
<history>
  <etap>
    <name>I этап – первый запуск космического аппарата</name>
    <text>Датой, когда началось освоение космоса считается 4 октября 1957 года – это день, когда Советский Союз в рамках своей космической программы первым запустил в космос космический аппарат – Спутник-1.  В этот день шарообразный спутник вышел на орбиту, передав обратно сигнал об успешном старте.
    Он был выведен на орбиту с помощью ракеты Р-7, спроектированной под руководством Сергея Королёва.  
    Силуэт Р-7, прародительницы всех последующих космических ракет, и сегодня узнаваем в суперсовременной ракете-носителе «Союз», 
    успешно отправляющей на орбиту «грузовики» и «легковушки» с космонавтами и туристами на борту — те же четыре «ноги» пакетной схемы и красные сопла.
    Полный виток вокруг Земли он совершал за 96 минут. «Звёздная жизнь» железного пионера космонавтики продлилась три месяца, но за этот период он прошёл фантастический путь в 60 миллионов км!
    Он был настолько популярен, что в Советском союзе в его форме делали даже ёлочные игрушки и значки. Освоение космического пространства СССР поставило точку на стараниях американцев первыми покорить космос. 
    Единственной целью его запуска была проверка теорий. В конце концов, освоение космоса в 50-60 годы перестало казаться призрачной задачей.
    Также это спровоцировало всплеск огромного количества научной фантастики, наводнившей страницы книг и экраны телевизоров.</text>
    <img>sputnik1-e1583497975384.jpg</img>
  </etap>
  <etap>
    <name>II этап – первые живые существа на орбите</name>
    <text>Успех первого запуска окрылял конструкторов, и перспектива отправить в космос живое существо и вернуть его целым и невредимым уже не казалась неосуществимой. 
    Всего через месяц после запуска «Спутника-1» на борту второго искусственного спутника Земли на орбиту отправилось первое животное — собака Лайка. 
    Цель у неё была почётная, но грустная — проверить выживаемость живых существ в условиях космического полёта. Более того, возвращение собаки не планировалось…
    Запуск и вывод спутника на орбиту прошли успешно, но после четырёх витков вокруг Земли из-за ошибки в расчётах температура внутри аппарата чрезмерно поднялась, 
    и Лайка погибла. Сам же спутник вращался в космосе ещё 5 месяцев, а затем потерял скорость и сгорел в плотных слоях атмосферы.
    Первыми лохматыми космонавтами, по возвращении приветствовавшими своих «отправителей» радостным лаем, стали  Белка и Стрелка, отправившиеся покорять небесные просторы на пятом спутнике в августе 1960 г. Их полёт длился чуть более суток, и за это время собаки успели облететь планету 17 раз.
    Всё это время за ними наблюдали с экранов мониторов в Центре управления полётами — кстати, именно по причине контрастности были выбраны белые собаки — ведь изображение тогда было чёрно-белым.
    По итогам запуска также был доработан и окончательно утверждён сам космический корабль — всего через 8 месяцев в аналогичном аппарате в космос отправится первый человек.
    В этот же период СССР запустил первый искусственный спутник Солнца, станция «Луна-2» сумела мягко прилуниться на поверхность планеты, а также были получены первые фотографии невидимой с Земли стороны Луны.</text>
    <img>s1200-1-e1583498055753.jpg</img>
  </etap>
  <etap>
    <name>III этап – выход человека в космос</name>
    <text>12 апреля 1961 года — совершён первый полёт человека в космос. 
     В 9:07 по московскому времени со стартовой площадки № 1 космодрома Байконур был запущен космический корабль «Восток-1» с первым в мире космонавтом на борту — Юрием Гагариным.
    Гагарин стал первым человеком, который отправился в космос и вернулся живым и невредимым на Землю.</text>
    <img>upload-TASS_1208569-pic905-895x505-22212.jpg</img>
  </etap>
  <etap>
    <name>IV этап – первая высадка на Луну</name>
    <text>Хотя Советский Союз первым вышел в космос и даже первым запустил на орбиту Земли человека, но США стали первыми, чьи астронавты смогли совершить удачную посадку на ближайшем космическом теле от Земли – на спутнике Луна.
    24 июля 1969 года два члена экипажа «Аполлон-11» ступили на поверхность Луны: Нил Армстронг и Базз Олдрин совершили один выход и пробыли на спутнике Земли два с половиной часа.
    Тогда была в новостях была сказана знаменитая фраза: «Это маленький шаг для человека, но огромный скачек для всего человечества».  
    Армстронгу не только удалось побывать на поверхности Луны, но и привезти пробы грунта на Землю.
    Всего с 1969 по 1972 год по программе «Аполлон» было выполнено 6 полётов с посадкой на Луне. За эти годы на спутнике побывало 12 человек.</text>
    <img>8144390629e94afa85a66ed3fae736d4.jpg</img>
  </etap>
  <etap>
    <name>V этап – исследование планет Солнечной системы</name>
    <text>Cоветская программа по изучению Венеры -  множество важнейших достижений и открытий.
    Советские аппараты выяснили, что у ближайшей соседки невероятно высокое давление и она никакой не близнец Земли. 
    В 1970 году «Венера-7 совершила первую в истории мягкую посадку, а пять лет спустя «Венера-9» передала первые фотографии с поверхности.
    Неофициально Венеру считали «советской» планетой, так как Союз прикладывал огромные усилия для её изучения, оставив Марс конкурентам.</text>
    <img>-аппарат-Венера-9-e1583498908630.jpg</img>
  </etap>
  <etap>
    <name>VI этап – человечество выходит за пределы Солнечной системы</name>
    <text>«Вояджер» (или «Путешественник») — проект NASA по исследованию дальних планет Солнечной системы — Юпитера, Сатурна, Нептуна, Урана и Плутона (который тогда ещё считался планетой), а также их спутников.
     «Вояджер-1» и «Вояджер-2» были запущены в 1977 году.
      Они впервые передали детальные цветные снимки дальних планет и в первый раз сфотографировали крупнейшие спутники.
      В 1977 г Вояжер-1 после изучения Юпитера и  Сатурна приступил к выполнению дополнительной миссии по исследованию отдалённых регионов Солнечной системы, включая пояс Койпера и границу гелиосферы.
      Вояджер-1» является самым быстрым из покидающих Солнечную систему космических аппаратов, а также наиболее удалённым от Земли объектом из созданных человеком.
      В 1972 году был запущен космический аппарат под названием «Пионер-10», который пройдя рядом с Сатурном, отправился за пределы Солнечной системы.
       И хотя «Пионер-10» не сообщил ничего нового о мире за пределами нашей системы, он стал доказательством, что выйти в другие системы человечество способно.</text>
    <img>Voyager.jpg</img>
  </etap>
  <etap>
    <name>VII этап –  начало международного комплексного изучение космоса</name>
    <text>Телескоп «Хаббл», выведенный на орбиту в 1990 году, стал «глазами» человечества. Орбитальный телескоп смог заглянуть так далеко, как никто прежде, и показать такие красоты Вселенной, каких и представить себе никто не мог.
      За 15 лет работы на околоземной орбите «Хаббл» получил 1,022 млн изображений небесных объектов — звёзд, туманностей, галактик, планет.
       Общий их объём данных, накопленный за всё время работы телескопа, составляет примерно 50 терабайт.
        Более 3900 астрономов получили возможность использовать его для наблюдений, опубликовано около 4000 статей в научных журналах.
      Ежегодно в списке 200 наиболее цитируемых статей не менее 10 % занимают работы, выполненные на основе материалов «Хаббла».</text>
    <img>HST-SM4.jpeg</img>
  </etap>
  <etap>
    <name>VIII этап – начало работы МКС (Международной космической станции)</name>
    <text>Международная космическая станция пришла на замену «Миру» в 1998 году. МКС почти в 5 раз больше предшественника и служит космической «дачей» для человечества по сей день.
        Одна из главных целей при создании станции – это возможность проведения различных опытов и экспериментов, которые требуют наличия уникальных условий космоса,
         а в частности – невесомости, а также вакуума и микрогравитации.</text>
    <img>space-International-Space-Station-1156552.jpg</img>
  </etap>
</history>
